# Generated by Django 5.2.17 on 2026-09-14 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("degree", models.CharField(max_length=255)),
                ("institution", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("exchange", "Exchange Semester"),
                        ],
                        default="bachelor",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
